.\cmake-build-debug\ctd.exe .\cmake-build-debug\example1.kpl > temp
fc /a temp .\cmake-build-debug\result1.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example2.kpl > temp
fc /a temp .\cmake-build-debug\result2.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example3.kpl > temp
fc /a temp .\cmake-build-debug\result3.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example4.kpl > temp
fc /a temp .\cmake-build-debug\result4.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example5.kpl > temp
fc /a temp .\cmake-build-debug\result5.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example6.kpl > temp
fc /a temp .\cmake-build-debug\result6.txt
.\cmake-build-debug\ctd.exe .\cmake-build-debug\example7.kpl > temp
fc /a temp .\cmake-build-debug\result7.txt